# -*- coding: utf-8 -*-
"""pdftosound.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mecTQyxSdZtt8clPJIbufFTiYHc62akD
"""

pip install pdfminer.six

pip install gTTS

from gtts import gTTS

import os

from pdfminer.high_level import extract_text

text = extract_text("Annexure.pdf")

mytext=text

language = 'en'

myobj = gTTS(text=mytext, lang=language, slow=False)

myobj.save("new.mp3")